# Generated by Django 5.0.6 on 2024-05-15 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('country', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('food', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2)])),
                ('rating', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('visited', models.BooleanField()),
            ],
        ),
    ]
